services:
  searxng:
    image: searxng/searxng
    container_name: SearXNG
    mem_limit: 8g
    cpu_shares: 2048
    security_opt:
      - no-new-privileges:true
    volumes:
      - /volume1/docker/searxng:/etc/searxng:rw 
    restart: on-failure:5
    ports:
      - 5147:8080

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    container_name: Perplexica-Backend
    environment:
      - SEARXNG_API_URL=http://192.168.1.2:5147
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - /volume1/docker/perplexica/data:/home/perplexica/data
      - /volume1/docker/perplexica/config/config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: on-failure:5

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://192.168.1.2:3001/api
        - NEXT_PUBLIC_WS_URL=ws://192.168.1.2:3001
    image: itzcrazykns1337/perplexica-frontend:main
    container_name: Perplexica-Frontend
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    restart: on-failure:5
